### ISSUE TITLE
Beta release checklist

### ISSUE THREAD

**Issue by tors** [tors/wt-go-sdk#1]
The list of things to do...

**Transfers**
- [x] Create transfer
- [x] Request for upload URL
- [x] Actual file upload to S3
- [x] Complete transfer
- [x] Finalize transfer
- [x] Find transfer

**Boards**
- [x] Create board
- [x] Add links to board
- [x] Add files to board
- [x] Request for upload URL
- [x] Actual file upload to S3
- [x] Complete file upload
- [x] Find board

**Integration tests**
Exercise the entire library against live WeTransfer API
- [x] Transfers
- [x] Boards
